### ISSUE TITLE
Disable Notifications

### ISSUE THREAD

**Issue by pbelmann** [deNBI/os_credits#2]
It would be useful to have a switch that disables all notifications. IMO disabled notifications should be the default.

**Comment by gilbus** [comment]
There is `NOTIFICATION_TO_OVERWRITE` which does not disable notifications but makes sure that they are only sent to the given address. Would this be enough?

**Comment by pbelmann** [comment]
Ok, yes that is enough. It is just an env variable I have to set, right?
